### ISSUE TITLE
Sound "Dope"

### ISSUE THREAD

**Issue by ugnelis** [Edvinas01/jelly-dude#45]
Sound "dope" is missing in game. Please fix it.
URL of the sound https://www.youtube.com/watch?v=vD_ZKcfZxbs

**Comment by Edvinas01** [comment]
@ugnelis When should it play?

**Comment by ugnelis** [comment]
@Edvinas01 when game is lost or harder object smashes Jelly Dude

**Comment by ugnelis** [comment]
Is this bug being solved?

**Comment by Edvinas01** [comment]
Bug is still present, @ugnelis can you make a pr?
